<a href="https://colab.research.google.com/github/fitriafifah/Mammographic-Masses-Clasification/blob/main/Naive_Bayes_dengan_Information_Gain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv('2sample_mammographic_masses.csv')
data.head()

BI-RADS assesment  Age  Margin  Severity
0                  4   64       5         0
1                  4   63       4         1
2                  4   24       1         0
3                  5   72       4         1
4                  4   63       1         0

In [ ]:
#variabel independen
x = data.drop(["Severity"], axis = 1)
x.head()

BI-RADS assesment  Age  Margin
0                  4   64       5
1                  4   63       4
2                  4   24       1
3                  5   72       4
4                  4   63       1

In [ ]:
#variabel dependen
y = data["Severity"]
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Severity, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
#mengaktifkan/memanggil/membuat fungsi klasifikasi Naive Bayes
modelnb = GaussianNB()

#memasukkan data training pada fungsi klasifikasi Naive Bayes
nbtrain = modelnb.fit(x_train, y_train)

In [ ]:
#menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])

In [ ]:
np.array(y_test)

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1])

In [ ]:
#menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[9.99584623e-01, 4.15377183e-04],
       [9.93526442e-01, 6.47355812e-03],
       [9.99753424e-01, 2.46575983e-04],
       [3.14888601e-02, 9.68511140e-01],
       [9.99874056e-01, 1.25943771e-04],
       [1.21515631e-02, 9.87848437e-01],
       [9.78627866e-01, 2.13721341e-02],
       [1.93571461e-02, 9.80642854e-01],
       [9.43533358e-02, 9.05646664e-01],
       [9.99214452e-01, 7.85547964e-04],
       [5.25619413e-02, 9.47438059e-01]])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4, 0],
       [2, 5]])

In [ ]:
#merapikan hasil confusion matrix
y_actual = pd.Series([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1], name = "actual")
y_pred = pd.Series([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1], name = "prediction")
df_confusion = pd.crosstab(y_actual, y_pred)
print(df_confusion)

prediction  0  1
actual          
0           4  0
1           2  5


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         4
           1       1.00      0.71      0.83         7

    accuracy                           0.82        11
   macro avg       0.83      0.86      0.82        11
weighted avg       0.88      0.82      0.82        11

